### DISCUSSION TITLE
如何导入自己的词典

### DISCUSSION THREAD

**Discussion by songxingling1** [Mintimate/oh-my-rime#178] [Q&A] [answered]
如题，不管是
- 在 `custom_simple.dict.yaml` 中使用 `import_tables` 导入自己的词典
- 在 `rime_mint.custom.yaml` 中使用 `engine/translators` 导入自己的词典

都无法导入词典，如何解决？

custom_simple.dict.yaml:
```yaml
# Rime dictionary
# encoding: utf-8
#
# 个性化词语 - by @Mintimate
# 建议自定义短语或者词语追加在这里
---
name: custom_simple
version: "2023.11.30"
sort: by_weight
import_tables:
  - oi
  - zhwiki
  - luogu
  - moegirl
  - develop
...

# 人名
# 常用语
哈哈	ha ha	99
macOS	mac	99
可以	ke yi	99
# 工具
颜文字	yan wen zi	100
# (｡>ㅅ<｡)
Mintimate	mintimate	1
https://www.mintimate.cn	mintimate	2
Mintimate's Blog	mintimate	3
# 输入法主题
碧皓青	bi hao qing	99
碧月青	bi yue qing	99
蓝水鸭	lan shui ya	99
黑水鸭	hei shui ya	99
```

rime_mint.custom.yaml:
```yaml
patch:
  "speller/algebra":
    - erase/^xx$/ # 首选保留
    - derive/^([zcs])h/$1/ # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/ # z, c, s => zh, ch, sh
    - derive/([ei])n$/$1ng/ # en => eng, in => ing
    - derive/([ei])ng$/$1n/ # eng => en, ing => in
    - derive/([aeiou])ng$/$1gn/        # dagn => dang
    - derive/([dtngkhrzcs])o(u|ng)$/$1o/  # zho => zhong|zhou
    - derive/ong$/on/                  # zhonguo => zhong guo
    - derive/ao$/oa/                   # hoa => hao
    - derive/([iu])a(o|ng?)$/a$1$2/    # tain => tian
    - abbrev/^([a-z]).+$/$1/ #简拼（首字母）
    - abbrev/^([zcs]h).+$/$1/ #简拼（zh, ch, sh）
  # "translator/dictionary": wanxiang
  # 语言模型
  "grammar/language": wanxiang-lts-zh-hans
  "grammar/collocation_max_length": 5
  "grammar/collocation_min_length": 2

  # translator 内加载
  "translator/contextual_suggestions": true
  "translator/max_homophones": 7
  "translator/max_homographs": 7
  "engine/translators/+":
    - table_translator@luogu
  luogu:
    dictionary: dicts/luogu
    enable_completion: false
    enable_sentence: false
    initial_quality: 9982
```
