### DISCUSSION TITLE
分享一份适用于ibus-rime的碧月青主题文件

### DISCUSSION THREAD

**Discussion by songxingling1** [Mintimate/oh-my-rime#179] [Show and tell]
如题，在gnome中，可以使用Customize ibus插件插件来自定义ibus外观，适用于ibus-rime的碧月青主题文件如下：

```css

 .candidate-page-button:hover {
  color: #E8E8E8;
  background-color: rgba(0, 0, 0, 0.12);
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button:selected, .candidate-page-button:active {
  color: #E8E8E8;
  background-color: rgba(0, 0, 0, 0.2);
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;}
 .candidate-page-button:last-child {
  border-radius: 0 0 16px 0;
}
 .candidate-page-button:first-child {
  border-radius: 0;
 }
 .candidate-page-button:checked {
  color: white;
  background-color: #0860F2;
  border: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button:insensitive {
  color: rgba(36, 36, 36, 0.45);
  background-color: transparent;
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button:focus {
  color: #242424;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button:focus {
  box-shadow: none !important;
}

 .candidate-page-button.flat {
  color: #242424;
  background-color: transparent;
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.flat:hover {
  color: #242424;
  background-color: rgba(0, 0, 0, 0.12);
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.flat:selected, .candidate-page-button.flat:active {
  color: #242424;
  background-color: rgba(0, 0, 0, 0.2);
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.flat:checked {
  color: #242424;
  background-color: rgba(0, 0, 0, 0.12);
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.flat:insensitive {
  color: rgba(36, 36, 36, 0.45);
  background-color: transparent;
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.flat:focus {
  color: #242424;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.flat:focus {
  box-shadow: none !important;
}

 .candidate-page-button.default {
  color: white;
  background-color: #0860F2;
  border: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.default:hover {
  color: white;
  border: none;
  text-shadow: none;
  icon-shadow: none;
  background-color: #176af3;
}

 .candidate-page-button.default:active {
  color: white;
  border: none;
  text-shadow: none;
  icon-shadow: none;
  background-color: #2673f4;
}

 .candidate-page-button.default:insensitive {
  color: white;
  background-color: #0860F2;
  border: none;
  text-shadow: none;
  icon-shadow: none;
}

 .candidate-page-button.default:focus {
  color: white;
  text-shadow: none;
  icon-shadow: none;
  box-shadow: none !important;
}

.candidate-index {
  padding: 0 0.5em 0 0;
  color: #B0B0B0;
}

.candidate-box:selected .candidate-index,.candidate-box:hover .candidate-index {
  color: #EFEFEF;
}

.candidate-box {
  padding: 0.3em 0.5em 0.3em 0.5em;
  margin-right: 0px;
  border-radius: 0;
  border-width: 0;
  color: #E8E8E8;
}
.candidate-box:first-child {
  padding: 0.3em 0.5em 0.3em 0.5em;
  margin-right: 0px;
  border-radius: 0 0 0 8px;
  border-width: 0;
  color: #E8E8E8;
}


.candidate-box:hover {
  background-color: #1CC883;
  color: #EFEFEF;
}

.candidate-box:active {
  background-color: rgba(0, 0, 0, 0.2);
  color: #242424;
}

.candidate-box:selected {
  background-color: #1CC883;
  color: #EFEFEF;
}

.candidate-box:last-child {
  margin-right: 0;
  border-radius: 0 0 8px 8px;
}

.candidate-page-button-box {
  height: 2em;
}

.vertical .candidate-page-button-box {
  padding-top: 0.5em;
}

.horizontal .candidate-page-button-box {
  padding-left: 0.5em;
}

.candidate-page-button-previous,
.candidate-page-button-next {
  border-radius: 6px;
}

.candidate-page-button-icon {
  icon-size: 1em;
}

.candidate-popup-content {
  background-color: #323232;
  border-radius: 8px;
  border-width: 0;
  box-shadow: 0 0px .7em 0 rgba(0, 0, 0, .3);

  color: #1CC883;
  margin: 3px 12px 17px 12px;
  spacing: 6px;
  padding: 0;
}
.candidate-popup-text {
  margin-top: .5em;
  margin-left: .5em;
  margin-bottom: .2em;
  margin-right: .5em;
}
.candidate-popup-boxpointer {
  -arrow-border-radius: 2px;
  -arrow-background-color: transparent;
  -arrow-border-width: 0;
  -arrow-border-color: transparent;
  -arrow-base: 64px;
  -arrow-rise: 12px;
  box-shadow: none;
  background-color: transparent;
  color: #565656;
  /* 修复当系统主题为黑色时指示框黑边 */
  border-image: none;
}

/* 结合系统调页按钮和IBUS样式的调页按钮 */
.candidate-page-button {
  color: #242424;
  background-color: transparent;
  border-color: transparent;
  box-shadow: none;
  text-shadow: none;
  icon-shadow: none;

  min-height: 1.5em;
  padding: 6px 12px;
  border: none;
  /* IBUS样式的调页按钮 */
  padding: 4px 6px !important;
}

```
创建一个 `.css` 文件，把内容复制进去，放在一个你喜欢的地方，之后
- 右键 Ibus 托盘
- 自定义 Ibus
- 主题
- 勾选自定义浅色主题 或 制定深色主题
- 选择你创建的 `.css` 文件，就生效了。

展示：
![image](https://github.com/user-attachments/assets/74b6af40-307d-4d80-83b0-43c9e3e6bfc0)

不喜勿喷qwq
