### DISCUSSION TITLE
问一个小白问题，转换为繁体后，有很多字被生硬地转换为生僻字，如何修改？

### DISCUSSION THREAD

**Discussion by MiaChaos** [Mintimate/oh-my-rime#21] [Q&A] [answered]
例如简体的：才会，吃饭
转为繁体后变成了纔會，喫飯，然而正常應該是才會，吃飯，纔對（才對）。
到底如何修正？
我用的是薄荷拼音

**Comment by Mintimate** [comment, marked as answer]
确实有这个问题，把opencc的风格有`s2t`改为台湾风格或者香港风格会好很多，比如: `吃饭`就会正常; 但是`才会`还是会变为生僻字: 
```yaml
# 简繁切换
transcription_cc:
  option_name: transcription
  opencc_config: s2t.json             # s2t.json | s2hk.json | s2tw.json | s2twp.json
  tips: none                          # 转换提示: all 都显示 | char 仅单字显示 | none 不显示。
  excluded_types: [ reverse_lookup ]  # 不转换反查（两分拼字）的内容
```

所有，我觉得要完整的繁体体验，应该要重新适配opencc、更改词库为繁体版本。目前词库是用雾凇拼音简体词库。
