### ISSUE TITLE
macOS系统添加default.custom.yaml修改候选词数量，重新部署、重启都无效

### ISSUE THREAD

**Issue by ChiehJang** [Mintimate/oh-my-rime#105]
系统版本：macOS Sonoma 14.5 
鼠须管版本：1.0.2
oh-my-rime也为最新。
default.custom.yaml文件内容
```
patch:
  schema_list:
    - schema: double_pinyin_flypy    # 小鹤双拼
  menu:
    page_size: 9
```
<img width="77" alt="SCR-20240613-jsmq" src="https://github.com/Mintimate/oh-my-rime/assets/11803185/7c4910ba-3343-4eb5-814d-21412333843a">
