### ISSUE TITLE
Color confusion

### ISSUE THREAD

**Issue by CassandraCat** [Mintimate/oh-my-rime#112]
```yaml
  mint_dark_blue:
    name: 黑水鸭／Mint Dark Blue
    author: Mintimate <"Mintimate's Blog">
    translucency: true                      
    mutual_exclusive: false               
    shadow_size: 0                         
    line_spacing: 5                       
    alpha: 1                                
    spacing: 10                             
    back_color: 0x424242                    
    hilited_candidate_back_color: 0xc6c01a  
    label_color: 0xefefef                  
    hilited_candidate_label_color: 0xefefef 
    candidate_text_color: 0xefefef          
    hilited_candidate_text_color: 0xefefef  
    comment_text_color: 0xefefef           
    hilited_comment_text_color: 0xffffff    
    text_color: 0x6495ed                   
    hilited_text_color: 0xc6c01a            
```

`0xc6c01a` should be a shade of yellow, but why does it appear as cyan in the rime?

like this:
<img width="484" alt="image" src="https://github.com/user-attachments/assets/ba4a3aec-0d30-4c84-88cb-277ae9b4af6e">
