### ISSUE TITLE
手机端如何使用小鹤辅助码

### ISSUE THREAD

**Issue by weikefan123** [Mintimate/oh-my-rime#119]
输入; 会和输入的文字一同上屏 无法使用辅助码 
设备是安卓小企输入法

**Comment by YummyCocoa** [comment]
修改双拼辅助码为其他可以用的键，比如逗号(`,`): 
```yaml
# double_pinyin_flypy.custom.yaml
# Rime schema
# encoding: utf-8

patch:
  # 设置激发键
  "axu_code/trigger_word": ","
  # 释放分号，并让逗号参与输入
  "speller/alphabet": zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA~,

```

重新部署后：

![重新部署后](https://github.com/user-attachments/assets/be3b1b61-2d7c-4362-be77-44c5550ec97b)
