### ISSUE TITLE
小鹤双拼薄荷定制+辅码方式 上屏错误,是哪里配置没激活么?

### ISSUE THREAD

**Issue by zwzcyeah** [Mintimate/oh-my-rime#125]
输入双拼+辅码,然后空格, 结果上屏的还是之前的候选字, 如下图:
![image](https://github.com/user-attachments/assets/75d47b9f-87dc-4641-9d19-4c899d313bf6)

**Comment by Mintimate** [comment]
分词配置占用了```，修改`"speller/delimiter"`的配置项。比如：
```yaml
# double_pinyin_flypy.custom.yaml
# encoding: utf-8

patch:
  "speller/alphabet": zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA` # 设置参与拼写不上屏元素
  "speller/delimiter": " ;"                                                 # 第一位<空格>是拼音之间的分隔符；第二位<;>表示可以手动输入单引号来分割拼音。
  "axu_code/trigger_word": '`'                                              # 辅码激发词
```
