### ISSUE TITLE
输入 Uu 拆字的时候，貌似无法用数字键选择候选词。

### ISSUE THREAD

**Issue by hoodlum1980** [Mintimate/oh-my-rime#142]
例如输入 “Uujinyu” 时，会有多个候选词，如果继续按数字键比如 “2”，2 会被追加成 “Uujinyu2”，而不是上屏列表中的第二个候选词。（而且也无法用 “，” “。” 按键翻页）不知道你们是不是有这个问题。按理说数字键应该和这个模式不冲突呀。

**Comment by Mintimate** [comment]
测试了薄荷输入方案内 小鹤混输 和 小鹤双拼 无法复现。用的薄荷配置，是仓库内最新分支么？之前修单字符和多字符匹配，有一段时间可能存在这个问题。

**Comment by hoodlum1980** [comment]
> 测试了薄荷输入方案内 小鹤混输 和 小鹤双拼 无法复现。用的薄荷配置，是仓库内最新分支么？之前修单字符和多字符匹配，有一段时间可能存在这个问题。

额，我是参考你的方案，我自己再配置的，合并到了自带的“朙月拼音-简体字”方案里面。~。~

**Comment by Mintimate** [comment]
那你应该是没配置好，看看是不是缺失`recognizer`部分，或者正则写的不一样。

`recognizer`配置和正则参考：
```yaml
# 反查映射
recognizer:
  import_preset: default
  patterns:
    url: "^[a-z]+[.].+$"
    punct: "^/([0-9]0?|[a-zA-Z]+)$"
    wubi98_mint: "Uw[a-z]*'?$"
    stroke: "Ui[a-z]*'?$"
    radical_lookup: "Uu[a-z]*'?$"
    rmb: "^R[0-9]+[.]?[0-9]*"        # 响应 lua_translator@number_translator 脚本将自动获取第 2 个字符作为触发前缀
    gregorian_to_lunar: "^N[0-9]{1,8}"  # 响应 lua_translator@Chinese_lunar_calendar 公历转农历，输入 N20240115 得到「二〇二四年腊月初五」，脚本将自动获取第 2 个字符作为触发前缀
    uppercase: ""  # 覆写默认的 uppercase 使其可以在输入大写后，输入数字
```
