### ISSUE TITLE
求助问题，自定义短语ok不生效，无法在第一个候选位

### ISSUE THREAD

**Issue by kirito41dd** [Mintimate/oh-my-rime#164]
<img width="560" alt="图片" src="https://github.com/user-attachments/assets/977e8fbe-cad9-49a8-ab78-896b4901cf44">

custom_phrase.txt：
```
# 此行之后不能写注释
BKB	bkb
应该	yingai
OK	ok	1000
```
rime_mint.custom.yaml：
```
patch:
  "engine/translators/+":
    - table_translator@custom_phrase           # 自定义短语 custom_phrase.txt

  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase  # 需要手动创建 custom_phrase.txt 文件
    db_class: stabledb
    enable_completion: false  # 补全提示
    enable_sentence: false    # 禁止造句
    initial_quality: 99       # custom_phrase 的权重应该比其他词库大
```

希望请教下有什么debug方法
