### ISSUE TITLE
如何在mac（Squirrel）上映射`Alt/Option`键？

### ISSUE THREAD

**Issue by Jacky-Lzx** [Mintimate/oh-my-rime#207]
## 问题描述

如何在mac（Squirrel）上映射`Alt/Option`键

## 尝试配置

`default.custom.yaml`中尝试添加如下配置

```yaml
patch:
  key_binder:
    bindings:
      - { when: has_menu, accept: "Control+k", send: Page_Up }
      - { when: has_menu, accept: "Control+j", send: Page_Down }
      - { when: has_menu, accept: "Control+h", send: Left }
      - { when: has_menu, accept: "Control+l", send: Right }

      - { when: has_menu, accept: "Alt+k", send: Page_Up }
      - { when: has_menu, accept: "Alt+j", send: Page_Down }
      - { when: has_menu, accept: "Alt+h", send: Left }
      - { when: has_menu, accept: "Alt+l", send: Right }
```

## 预期结果

在选择时，可以通过`Control+k`以及`Alt+k`等按键进行选择

## 当前结果

`Control+k`等绑定Control的快捷键可以正常工作，`Alt+k`等绑定Alt的快捷键不能使用
