### ISSUE TITLE
翻页配置快捷键按文档配置为  [ ]  不生效

### ISSUE THREAD

**Issue by randomxiang** [Mintimate/oh-my-rime#42]
表现：翻页配置快捷键更改为  [ ]  不生效，且注释- =进行翻页后还可以用

文档：https://www.mintimate.cc/zh/guide/shortcutKeys.html
配置步骤：
1. rime_mint.schema.yaml 更新为新的键位
2. 重新部署
3. 重启电脑

<img width="1156" alt="截屏2024-03-16 13 18 27" src="https://github.com/Mintimate/oh-my-rime/assets/24973199/f9813741-c12d-4469-bc52-6c3936a3c755">
<img width="276" alt="截屏2024-03-16 13 19 00" src="https://github.com/Mintimate/oh-my-rime/assets/24973199/5f6a80e8-5ad4-4bd8-95bb-cdc9fc575b3d">
<img width="248" alt="截屏2024-03-16 13 19 22" src="https://github.com/Mintimate/oh-my-rime/assets/24973199/6880b7a7-7542-4005-997d-f63e3dee7544">

**Comment by Mintimate** [comment]
目前`[`和`]`被以词定字所占用，如果不需要，可以删除以词定字：
engine:
  processors:
    - lua_processor@*select_character              # 以词定字
```

也可以定义`select_first_character`和`select_last_character`，使其释放`[`和`]`：
```yaml
key_binder:
  import_preset: default
  select_first_character: "minus" # 使用 - 
  select_last_character: "equal"  # 使用 =
  bindings:
    - {accept: "Control+Shift+E", toggle: emoji_suggestion, when: always}
    - {accept: "Control+Shift+exclam", toggle: transcription, when: has_menu}
    - {accept: "Control+Shift+1", toggle: transcription, when: has_menu}
    - {accept: bracketleft, send: Page_Up, when: paging}      # 使用`[`进行向上翻页（第一页时候无效）
    - {accept: bracketright, send: Page_Down, when: has_menu} # 使用`]`进行向下翻页
```

具体可以看`select_character.lua`文件内部的按键映射：
```lua
   -- 选择开头字
   local first_key = config:get_string('key_binder/select_first_character') or 'bracketleft'
   -- 选择末尾字
   local last_key = config:get_string('key_binder/select_last_character') or 'bracketright'
```
