### ISSUE TITLE
咨询下同步rime-ice词库的action是否可以分享下呢？

### ISSUE THREAD

**Issue by plutotree** [Mintimate/oh-my-rime#52]
在'.github/workflows`下面好像没看到同步rime-ice词库的流程，在[action](https://github.com/Mintimate/oh-my-rime/actions)页面也没有看到，想问下这块流程是怎么自动触发的呢？是否可以分享下呢？

**Comment by Mintimate** [comment]
当时写地球词库转换时候一起写的，所以在另外一个库里： https://github.com/Mintimate/RimeTerraDictBuilder

后来想想也挺合理，可以减小此仓库非rime配置的体积。

**Comment by plutotree** [comment]
> 当时写地球词库转换时候一起写的，所以在另外一个库里： https://github.com/Mintimate/RimeTerraDictBuilder
> 
> 后来想想也挺合理，可以减小此仓库非rime配置的体积。

感谢，我也自己写了一个，由于项目是私有的，贴在这里，供需要的参考下：

```yaml
name: Update rime dict
on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my_workspace
        uses: actions/checkout@master
        with:
          path: my_workspace
      - name: Checkout rime-ice
        uses: actions/checkout@master
        with:
          repository: iDvel/rime-ice
          path: rime-ice
      - name: Copy rime-ice dicts
        run: |
          dst="my_workspace/rime/dicts"
          cp rime-ice/en_dicts/en.dict.yaml $dst/en_dicts/rime_ice.en.dict.yaml
          cp rime-ice/en_dicts/en_ext.dict.yaml $dst/en_dicts/rime_ice.en_ext.dict.yaml
          cp rime-ice/cn_dicts/8105.dict.yaml $dst/rime_ice.8105.dict.yaml
          cp rime-ice/cn_dicts/base.dict.yaml $dst/rime_ice.base.dict.yaml
          cp rime-ice/cn_dicts/ext.dict.yaml $dst/rime_ice.ext.dict.yaml
          cp rime-ice/cn_dicts/tencent.dict.yaml $dst/rime_ice.tencent.dict.yaml
      - name: Commit & Push changes rime-ice dicts
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: my_workspace
          message: "autoupdate: sync rime-ice dict"
```
