### ISSUE TITLE
是否可以实现“用CTL来切换中英文，使用左右shift来做第2、3候选词的选择”？

### ISSUE THREAD

**Issue by netvolcano** [Mintimate/oh-my-rime#90]
以前一直使用拼音加加的，可以“用CTL来切换中英文，使用左右shift来做第2、3候选词的选择”，感觉这个方式非常方便。

自己做了一些配置如下后，基本可以实现（缺点是：不能方便地进行中英文混合输入了，一旦想按住shift来输入大写字母，总是触发选字，希望有大侠可以帮忙改进一下）。
```
patch:
key_binder/bindings/+:
  # 添加 , 和 . 翻页
  - { when: paging, accept: comma, send: Page_Up }
  - { when: has_menu, accept: period, send: Page_Down }
  # 使用左右shift来选择第2、3候选字
  - { when: has_menu, accept: "Shift+Shift_L", send: 2 }
  - { when: has_menu, accept: "Shift+Shift_R", send: 3 }

使用 CTL 来切换中西文
"ascii_composer/switch_key":
  Caps_Lock: clear
  Control_L: commit_code
  Control_R: commit_code
  Eisu_toggle: clear
  Shift_L: noop
  Shift_R: noop
```
